version: "3"

services:
  crontab:
    image: lvinkim/php-env-docker:latest
    depends_on:
      - redis
    volumes:
      - ".:/var/www/html"
      - "${INPUT_DIRECTORY}:${INPUT_DIRECTORY}"
      - ./xdebug.disable.ini:/etc/php/7.2/mods-available/xdebug.ini
    working_dir: '/var/www/html'
    restart: always
    command:
      - /usr/bin/env
      - php
      - bin/crontab.php
    networks:
      - appnet

  redis:
    image: redis:4.0
    volumes:
      - redisdata:/data
    expose:
      - 6379
    restart: always
    networks:
      - appnet

volumes:
  redisdata:
    driver: local

networks:
  appnet: