version: "3"

services:
  app:
    image: lvinkim/php-env-docker:latest
    depends_on:
      - redis
    ports:
      - ${APP_EXPORT_PORT}:80
    volumes:
      - ".:/var/www/html"
      - "${INPUT_DIRECTORY}:${INPUT_DIRECTORY}"
    working_dir: '/var/www/html'
    restart: always
    command:
      - /usr/bin/env
      - php
      - -S
      - 0.0.0.0:80
      - -t
      - public
    networks:
      - appnet

  crontab:
    image: lvinkim/php-env-docker:latest
    depends_on:
      - redis
    volumes:
      - ".:/var/www/html"
      - "${INPUT_DIRECTORY}:${INPUT_DIRECTORY}"
    working_dir: '/var/www/html'
    restart: always
    command:
      - /usr/bin/env
      - php
      - bin/crontab.php
    networks:
      - appnet

  redis:
    image: redis:4.0
    volumes:
      - redisdata:/data
    expose:
      - 6379
    restart: always
    networks:
      - appnet

  admin:
    image: erikdubbelboer/phpredisadmin
    depends_on:
      - redis
    ports:
      - ${CACHE_REDIS_ADMIN_PORT}:80
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASS=${CACHE_REDIS_ADMIN_PASS}
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
    networks:
      - appnet

volumes:
  redisdata:
    driver: local

networks:
  appnet: