version: "3"

services:
  app:
    image: lvinkim/php-env-docker:latest
    volumes:
      - ".:/var/www/html"
      - "${INPUT_DIRECTORY}:${INPUT_DIRECTORY}"
    working_dir: '/var/www/html'
    restart: always
    command:
      - php
      - app/main.php

  crontab:
    image: lvinkim/php-env-docker:latest
    volumes:
      - ".:/var/www/html"
      - "${INPUT_DIRECTORY}:${INPUT_DIRECTORY}"
    working_dir: '/var/www/html'
    restart: always
    command:
      - /usr/bin/env
      - php
      - bin/crontab.php
